---
title: "Data visualization"
author: "Lia Domke"
date: "11/7/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F, warning = F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(leaflet)
library(scales)
library(DT)
```

# Prepare data

```{r}
# tryCatch - allows you to prevent errors, try to read in the data locally. If it has an error it will catch it and then you give it what to do if the error happens. Can also use ifelse, but tryCatch can be used if you dont what kind of errors will be thrown. 

data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        write.csv(esc, "data/escapement.csv", row.names = F)
        return(esc)
    }
)

head(esc)
```
Total escapement by Species, Region, Year
  * only for Sockeye, Chinook, Coho, Pink, Chum
  
```{r}
annual_esc<- esc %>% 
  # filter(Species == "Sockeye" | Species == "Chinook" | Species == "Coho" | Species == "Pink" | Species ==   ("Chum")) %>% 
  filter(Species %in% c("Sockeye", "Chinook", "Coho", "Pink", "Chum")) %>% # use == only when comparing one to one species, in the # code above it would get the same as using %in% but only because I repeated Species each time. IF you try and use Species == c(species list, sp1, sp2) it wont give the same answer. Not useful.
  separate(sampleDate, into = c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarise(escapement = sum(DailyCount))
```
  

# Create static plots

```{r}
# geom_col creates a stacked plot by year. default for geom_col is to sum the values. 
# geom_bar has different defaults for its mathetatical operations
ggplot(annual_esc, mapping = aes(x = Species, y = escapement)) + geom_col(fill = "blue")
```

```{r}
ggplot(annual_esc, mapping = aes(x = Species, y = escapement, fill = SASAP.Region)) + geom_col()
```

```{r}
kodiak_esc <- annual_esc %>% 
  filter(SASAP.Region == "Kodiak")

# can save theme calls as an object in R
mytheme <- theme_bw() + # there is a separate package called ggthemes that has even more options
  theme(legend.position = "bottom") # theme call came AFTER theme_bw, if its opposite it will overwrite everything. can also use numbers to specify the coordinates. 
# can also create themes as functions and put into your package and share across an organization or with yourself. 

pal <- c("blue", "green", "black", "orange", "magenta")

ggplot(kodiak_esc, mapping = aes(x = Year, y = escapement, color = Species)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = pal) +
  scale_y_continuous(labels = comma) + # allows you change aspects of your y axis labels, comma is function from scales another one would be labels = percent. 
  ylab("Escapement (num.fish)") +
  ggtitle("Kodiak Salmon Escapement") +
  mytheme

# go to Rcolor.pdf stat.columbia.edu has pdf of like all the colors available
# saving your figure as a jpg (flat) makes it harder for programs to read the plot. Might need a vectorized image. 
```

Create multiple plots by a factor within your dataframe
```{r, fig.heigh = 7, fig.width = 4}
ggplot(annual_esc, mapping = aes(x = Year, y = escapement, color = Species)) +
  geom_line() +
  geom_point() +
  facet_wrap(~SASAP.Region, ncol = 2, scales = "free_y") +
  scale_y_continuous(labels = comma) +
  ylab("Escapement (num.fish)") +
  mytheme
```

# Create an interactive table

```{r}
locations <- esc %>%
  distinct(Location, Latitude, Longitude) %>% # will pull out distinct combinations  
  drop_na() # will drop any row and any column that have nas, na.omit works on the columns but drop_na works on everything

```

```{r}
datatable(locations)
```


# Create an interative map

```{r}
# Basic plot
leaflet(locations) %>% 
  addProviderTiles(providers$Esri.WorldStreetMap) %>% # essentially add rasters onto the the map to create more detailed info. 
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~Location) # model our longitude column onto lng argument 
```


```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T, # line around the markers
                   weight = 0.5,
                   color = "white",
                   opacity = 1)

# some tiles servers require a apn key and so those are less open then the 
```

